Vagrant.configure("2") do |config|
    config.vm.define "control", primary: true do |web|
      web.vm.box = "ubuntu/focal64"
    end
  
    config.vm.define "worker1" do |db|
      db.vm.box = "ubuntu/focal64"
    end

    config.vm.define "worker2" do |db|
        db.vm.box = "ubuntu/focal64"
    end

    # (1..2).each do |i|
    #     config.vm.define "worker#{i}" do |worker|
    #         db.vm.box = "ubuntu/focal64"
    #     end
    # end
end